language: python
sudo: false
cache:
  pip: false
jobs:
  include:
  - stage: unit tests
    python: '3.6'
    install:
    - pip install six
    - python setup.py install
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-test.txt
    - pip install codacy-coverage
    script:
    - if [ "$TRAVIS_BRANCH" != "doc" ]; then
      invoke test --no-flake --no-post; fi
    after_success:
    - echo "finished running tests on repo"
    - python-codacy-coverage -r coverage.xml
