language: python
sudo: false
cache:
  pip: false
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
jobs:
  include:
  - stage: unit tests
    python: '3.6'
    install:
    - pip install six
    - pip install -U -r requirements-test.txt
    - pip install -U -r requirements.txt
    - python setup.py install
    - pip install codacy-coverage
    script:
    - if [ "$TRAVIS_BRANCH" != "doc" ]; then
      invoke test --no-flake --no-post; fi
    - if [ "$TRAVIS_BRANCH" == "production" ]; then
      invoke test --deployment; fi
    after_success:
    - echo "finished running tests on repo"
    - python-codacy-coverage -r coverage.xml
    - if [ "$TRAVIS_BRANCH" == "production" ]; then
      tibanna_4dn deploy_pony;
      tibanna_4dn deploy_core -n start_run;
      tibanna_4dn deploy_core -n run_task;
      tibanna_4dn deploy_core -n check_task;
      tibanna_4dn deploy_core -n update_ffmeta;
      tibanna_cgap deploy_zebra;
      tibanna_cgap deploy_core -n start_run;
      tibanna_cgap deploy_core -n run_task;
      tibanna_cgap deploy_core -n check_task;
      tibanna_cgap deploy_core -n update_ffmeta;
      tibanna_4dn deploy_pony -g default luisa -S;
      tibanna_4dn deploy_core -g default luisa -n start_run;
      tibanna_4dn deploy_core -g default luisa -n run_task;
      tibanna_4dn deploy_core -g default luisa -n check_task;
      tibanna_4dn deploy_core -g default luisa -n update_ffmeta;
      fi
