# Deployment for Tibanna_ff

name: deploy-prod

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Build
        run: |
          pip install tibanna
          python setup.py install
          pip install -r requirements-test.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test + Deploy
        env:
          S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
        run: 
          invoke test --deployment
          tibanna_4dn deploy_pony
          tibanna_4dn deploy_core -n start_run
          tibanna_4dn deploy_core -n run_task
          tibanna_4dn deploy_core -n check_task
          tibanna_4dn deploy_core -n update_ffmeta
          tibanna_cgap deploy_zebra
          tibanna_cgap deploy_core -n start_run
          tibanna_cgap deploy_core -n run_task
          tibanna_cgap deploy_core -n check_task
          tibanna_cgap deploy_core -n update_ffmeta
          tibanna_cgap deploy_zebra -s tmp_md5
          tibanna_cgap deploy_core -n start_run -s tmp_md5
          tibanna_cgap deploy_core -n run_task -s tmp_md5
          tibanna_cgap deploy_core -n check_task -s tmp_md5
          tibanna_cgap deploy_core -n update_ffmeta -s tmp_md5
          tibanna_4dn deploy_pony -g default_luisa -S
          tibanna_4dn deploy_core -g default_luisa -n start_run
          tibanna_4dn deploy_core -g default_luisa -n run_task
          tibanna_4dn deploy_core -g default_luisa -n check_task
          tibanna_4dn deploy_core -g default_luisa -n update_ffmeta
          tibanna_4dn deploy_pony -s tmp_md5
          tibanna_4dn deploy_core -n start_run -s tmp_md5
          tibanna_4dn deploy_core -n run_task -s tmp_md5
          tibanna_4dn deploy_core -n check_task -s tmp_md5
          tibanna_4dn deploy_core -n update_ffmeta -s tmp_md5
          
